# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN apk add --no-cache python3 make g++ && \
    yarn install --production --frozen-lockfile && \
    apk del python3 make g++

# Copy source and build
COPY . .
RUN npm run build

# Default command
CMD ["node", "dist/server.js"]
